apiVersion: v1
kind: Namespace
metadata:
  name: coroot
  labels:
    # Required for eBPF node agent to run with privileged access
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
